# Generated by Django 5.1.2 on 2024-11-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('img', models.ImageField(blank=True, null=True, upload_to='seller/', verbose_name='Фото профиля')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Номер телефона')),
            ],
        ),
    ]
