# Generated by Django 5.1.2 on 2024-11-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('engine_capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объем двигателя')),
                ('type_of_fuel', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электрика')], max_length=10)),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('state', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], max_length=10)),
                ('box', models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат')], max_length=10)),
                ('steering_wheel', models.CharField(choices=[('left', 'Левый'), ('right', 'Правый')], max_length=10)),
                ('kuzov', models.CharField(max_length=100, verbose_name='Кузов')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='models.vehicle')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
