# Generated by Django 5.1.2 on 2024-11-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
