# Generated by Django 5.1.2 on 2024-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_vehicle_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='box',
            field=models.CharField(choices=[('Механика', 'Механика'), ('Автомат', 'Автомат')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='state',
            field=models.CharField(choices=[('Новый', 'Новый'), ('БУ', 'Б/у')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='steering_wheel',
            field=models.CharField(choices=[('Левый', 'Левый'), ('Правый', 'Правый')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type_of_fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Электрика', 'Электрика')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicle/images/', verbose_name='Изображение'),
        ),
    ]
