# Generated by Django 5.1.2 on 2024-11-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_vehicleimage_options_alter_vehicle_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='file',
            field=models.FileField(default=1, upload_to='vehicle/images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
