# Generated by Django 5.1.2 on 2024-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_vehicleimage_image_vehicleimage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='file',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(default=1, upload_to='vehicle/images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
