# Generated by Django 5.1.2 on 2024-11-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_remove_vehicleimage_file_vehicleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата загрузки'),
        ),
    ]
