# Generated by Django 5.1.2 on 2024-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_vehicleimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
