# Generated by Django 5.1.2 on 2024-11-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_vehicle_box_alter_vehicle_name_and_more'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller', verbose_name='Продавец'),
        ),
    ]
