# Generated by Django 5.1.2 on 2024-11-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
